# Site settings
title: Lionel Pigou
title-fontcolor: white
# header-img: img/images/420902.png
# header-img: img/images/abstract-pattern_00173817.jpg
# header-img: img/images/Abstract-Pattern-147.jpg
# header-img: img/images/Abstract-Pattern-l.jpg
# header-img: img/images/big_1e7e5d75ed02926661f6458f3acbffc852a2adfb.jpg
# header-img: img/images/Blue-Navy-Pattern-l.jpg
# header-img: img/images/down_bokeh_lights.jpg
# header-img: img/images/Feather-Pattern-Abstract-1893-1920x1080.jpg
# header-img: img/images/header-triangle-pattern.jpg
# header-img: img/images/the-blue-lines-pattern.jpg
# header-img: img/images/wallhaven-2921.png
# header-img: img/images/hipster-wallpaper-9964-10319-hd-wallpapers.jpg
# header-img: img/images/4.jpg
# header-img: img/images/20090103-ghent-at-night-21 (1).jpg
# header-img: img/images/69153_169543409727831_3424714_n.jpg
# header-img: img/images/images.jpg

# header-img: img/images/images (1).jpg
# header-img: img/images/wallhaven-6526.jpg
# header-img: img/images/pattern-header.jpg
# header-img: img/images/PatternHeader-Blue.jpg
# header-img: img/images/ws_Abstract_Colorful_Pattern_1280x1024.jpg
# header-img: img/images/wallhaven-10243.jpg
# header-img: img/images/6859542-hipster-wallpaper.jpg
# header-img: img/images/1.jpg
# header-img: img/images/2.jpg
# header-img: img/images/3.jpg
# header-img: img/banner-gesture-dark1.jpg
# header-img: img/DSCF1723.JPG
# header-img: img/ghent4.jpg
# header-img: img/ghent3.jpg
# header-img: img/Ghent-2.jpg

header-img: img/gent1o.jpg
# header-img: img/gent1 (3).jpg
# header-img: img/home-bg2.jpg



email: lionelpigou@gmail.com
description: "Lionel Pigou"
baseurl: ""
url: "http://lpigou.github.io/"
twitter_username: lpigou
github_username:  lpigou
facebook_username:  
linkedin: https://be.linkedin.com/pub/lionel-pigou/66/b91/452/en
google_plus: https://plus.google.com/112938237397375157411/posts

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 1000
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","Gemfile.lock","Gemfile","Guardfile"]
